# Generated by Django 4.0.4 on 2022-05-09 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downtown', models.CharField(max_length=150, unique=True, verbose_name='alcaldia')),
                ('cp', models.IntegerField(max_length=10, unique=True, verbose_name='cp')),
                ('street', models.CharField(max_length=200, unique=True, verbose_name='calle')),
                ('status', models.BooleanField(default=True, verbose_name='estado')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('first_name', models.CharField(max_length=30, verbose_name='apellido_materno')),
                ('second_name', models.CharField(max_length=30, verbose_name='apellido_paterno')),
                ('apodo', models.CharField(max_length=30, null=True, verbose_name='apodo')),
                ('curp', models.CharField(max_length=18, unique=True, verbose_name='curp')),
                ('rfc', models.CharField(max_length=13, unique=True, verbose_name='rfc')),
                ('mail', models.EmailField(max_length=254, unique=True, verbose_name='correo')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrendadora.address')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
