# Generated by Django 4.0.4 on 2022-05-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='apodo',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='apodo'),
        ),
    ]
