# Generated by Django 4.0.4 on 2022-05-09 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0002_alter_owner_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='cp',
            field=models.IntegerField(unique=True, verbose_name='cp'),
        ),
    ]
