# Generated by Django 4.0.4 on 2022-05-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0003_alter_address_cp'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='int',
            field=models.IntegerField(default=1, unique=True, verbose_name='interior'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='number',
            field=models.IntegerField(default=1, unique=True, verbose_name='numero'),
            preserve_default=False,
        ),
    ]
