# Generated by Django 4.0.4 on 2022-05-20 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0003_remove_owner_curp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Town',
            new_name='State',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='town',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='colonia',
        ),
    ]
