# Generated by Django 4.0.4 on 2022-05-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0004_rename_town_state_rename_town_owner_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='interior',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='interior'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Estado'),
        ),
    ]
