# Generated by Django 4.0.4 on 2022-05-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0004_address_int_address_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='int',
        ),
        migrations.AddField(
            model_name='address',
            name='interior',
            field=models.PositiveIntegerField(default=1, unique=True, verbose_name='interior'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='cp',
            field=models.PositiveIntegerField(unique=True, verbose_name='cp'),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.PositiveIntegerField(unique=True, verbose_name='numero'),
        ),
    ]
