# Generated by Django 4.0.4 on 2022-05-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0005_remove_address_int_address_interior_alter_address_cp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='status',
        ),
        migrations.AddField(
            model_name='owner',
            name='status',
            field=models.CharField(default=True, max_length=10, verbose_name='estado'),
        ),
    ]
