# Generated by Django 4.0.4 on 2022-05-20 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0005_alter_owner_interior_alter_state_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidad',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='unidad',
            name='placas',
        ),
        migrations.RemoveField(
            model_name='unidad',
            name='submarca',
        ),
        migrations.RemoveField(
            model_name='unidad',
            name='year',
        ),
    ]
