# Generated by Django 4.0.4 on 2022-05-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0006_remove_unidad_marca_remove_unidad_placas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='tasa',
            field=models.PositiveIntegerField(verbose_name='Tasa'),
        ),
    ]
