# Generated by Django 4.0.4 on 2022-05-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0006_remove_address_status_owner_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='address',
        ),
        migrations.AddField(
            model_name='owner',
            name='cp',
            field=models.PositiveIntegerField(default=1, unique=True, verbose_name='cp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='downtown',
            field=models.CharField(default=1, max_length=150, unique=True, verbose_name='alcaldia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='interior',
            field=models.PositiveIntegerField(default=1, unique=True, verbose_name='interior'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='number',
            field=models.PositiveIntegerField(default=1, unique=True, verbose_name='numero'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='street',
            field=models.CharField(default=1, max_length=200, unique=True, verbose_name='calle'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
