# Generated by Django 4.0.4 on 2022-05-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0007_alter_unidad_tasa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='correo'),
        ),
    ]
