# Generated by Django 4.0.4 on 2022-05-10 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0008_alter_owner_first_name_alter_owner_second_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='col',
            field=models.CharField(default=1, max_length=200, unique=True, verbose_name='colonia'),
            preserve_default=False,
        ),
    ]
