# Generated by Django 4.0.4 on 2022-05-31 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0008_alter_owner_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='capital',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9, verbose_name='capital'),
            preserve_default=False,
        ),
    ]
