# Generated by Django 4.0.4 on 2022-05-31 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0009_owner_capital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='capital',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='capital'),
        ),
    ]
