# Generated by Django 4.0.4 on 2022-05-10 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0009_owner_col'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='status',
            field=models.CharField(default='Activo', max_length=10, verbose_name='estado'),
        ),
    ]
