# Generated by Django 4.0.4 on 2022-05-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0010_alter_owner_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='cp',
            field=models.PositiveIntegerField(max_length=15, unique=True, verbose_name='cp'),
        ),
    ]
