# Generated by Django 4.0.4 on 2022-06-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0010_alter_owner_capital'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='comentarios',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='comentario'),
        ),
        migrations.AddField(
            model_name='register',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='referencia'),
        ),
    ]
