# Generated by Django 4.0.4 on 2022-05-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0011_alter_owner_cp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='interior',
            field=models.PositiveIntegerField(null=True, unique=True, verbose_name='interior'),
        ),
    ]
