# Generated by Django 4.0.4 on 2022-06-01 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0012_remove_register_unidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conceptos',
            name='tipo',
        ),
        migrations.AddField(
            model_name='tipo',
            name='concepto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='arrendadora.conceptos'),
            preserve_default=False,
        ),
    ]
