# Generated by Django 4.0.4 on 2022-05-10 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0012_alter_owner_interior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='col',
            field=models.CharField(max_length=200, verbose_name='colonia'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='cp',
            field=models.PositiveIntegerField(max_length=15, verbose_name='cp'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='downtown',
            field=models.CharField(max_length=150, verbose_name='alcaldia'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='interior',
            field=models.PositiveIntegerField(null=True, verbose_name='interior'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='street',
            field=models.CharField(max_length=200, verbose_name='calle'),
        ),
    ]
