# Generated by Django 4.0.4 on 2022-05-10 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0013_alter_owner_col_alter_owner_cp_alter_owner_downtown_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='cp',
            field=models.PositiveIntegerField(verbose_name='cp'),
        ),
    ]
