# Generated by Django 4.0.4 on 2022-06-01 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0013_remove_conceptos_tipo_tipo_concepto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo',
            name='concepto',
        ),
        migrations.AddField(
            model_name='conceptos',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='arrendadora.tipo'),
            preserve_default=False,
        ),
    ]
