# Generated by Django 4.0.4 on 2022-05-10 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0014_alter_owner_cp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Estatus')),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Alcaldia')),
            ],
        ),
        migrations.RemoveField(
            model_name='owner',
            name='downtown',
        ),
        migrations.AddField(
            model_name='owner',
            name='town',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='arrendadora.town'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrendadora.status'),
        ),
    ]
