# Generated by Django 4.0.4 on 2022-05-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0015_status_town_remove_owner_downtown_owner_town_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='town',
        ),
        migrations.AddField(
            model_name='owner',
            name='downtown',
            field=models.CharField(default=1, max_length=150, verbose_name='alcaldia'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Town',
        ),
    ]
