# Generated by Django 4.0.4 on 2022-05-10 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0016_remove_owner_town_owner_downtown_delete_town'),
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Alcaldia')),
            ],
        ),
        migrations.RemoveField(
            model_name='owner',
            name='downtown',
        ),
        migrations.AddField(
            model_name='owner',
            name='town',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='arrendadora.town'),
            preserve_default=False,
        ),
    ]
