# Generated by Django 4.0.4 on 2022-05-10 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0018_area_owner_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suburb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Barrio')),
            ],
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='col',
            new_name='colonia',
        ),
        migrations.AddField(
            model_name='owner',
            name='suburb',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='arrendadora.suburb'),
            preserve_default=False,
        ),
    ]
