# Generated by Django 4.0.4 on 2022-05-10 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0019_suburb_rename_col_owner_colonia_owner_suburb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Colonia')),
            ],
        ),
        migrations.AlterField(
            model_name='owner',
            name='colonia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrendadora.colonia'),
        ),
    ]
