# Generated by Django 4.0.4 on 2022-05-10 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0020_colonia_alter_owner_colonia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='suburb',
        ),
        migrations.DeleteModel(
            name='Suburb',
        ),
    ]
