# Generated by Django 4.0.4 on 2022-05-10 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0024_remove_town_colonia_owner_colonia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Alcaldia')),
            ],
        ),
        migrations.AddField(
            model_name='colonia',
            name='calle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='arrendadora.calle'),
            preserve_default=False,
        ),
    ]
