# Generated by Django 4.0.4 on 2022-05-10 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0025_calle_colonia_calle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colonia',
            name='calle',
        ),
        migrations.DeleteModel(
            name='Calle',
        ),
    ]
