# Generated by Django 4.0.4 on 2022-05-10 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0026_remove_colonia_calle_delete_calle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Modelo')),
            ],
        ),
        migrations.CreateModel(
            name='Submarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Submarca')),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Unidad')),
                ('placas', models.CharField(max_length=50, verbose_name='Placas')),
                ('year', models.PositiveIntegerField(verbose_name='Año')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrendadora.marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrendadora.modelo')),
                ('submarca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrendadora.submarca')),
            ],
        ),
        migrations.AddField(
            model_name='owner',
            name='unidad',
            field=models.ManyToManyField(null=True, to='arrendadora.unidad'),
        ),
    ]
