# Generated by Django 4.0.4 on 2022-05-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0027_marca_modelo_submarca_unidad_owner_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='unidad',
            field=models.ManyToManyField(to='arrendadora.unidad'),
        ),
    ]
