# Generated by Django 4.0.4 on 2022-05-10 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0028_alter_owner_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='modelo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='arrendadora.modelo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marca',
            name='submarca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='arrendadora.submarca'),
            preserve_default=False,
        ),
    ]
