# Generated by Django 4.0.4 on 2022-05-10 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0029_marca_modelo_marca_submarca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidad',
            name='modelo',
        ),
        migrations.AlterField(
            model_name='modelo',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrendadora.modelo'),
        ),
    ]
