# Generated by Django 4.0.4 on 2022-05-10 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0031_remove_unidad_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='arrendadora.status'),
            preserve_default=False,
        ),
    ]
