# Generated by Django 4.0.4 on 2022-05-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0032_unidad_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='unidad',
            field=models.ManyToManyField(null=True, to='arrendadora.unidad'),
        ),
    ]
