# Generated by Django 4.0.4 on 2022-05-10 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0033_alter_owner_unidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tipo')),
            ],
        ),
        migrations.AlterField(
            model_name='owner',
            name='unidad',
            field=models.ManyToManyField(to='arrendadora.unidad'),
        ),
        migrations.CreateModel(
            name='Conceptos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Concepto')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrendadora.tipo')),
            ],
        ),
    ]
