# Generated by Django 4.0.4 on 2022-05-10 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0034_tipo_alter_owner_unidad_conceptos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='unidad',
        ),
        migrations.AddField(
            model_name='owner',
            name='unidad',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='arrendadora.unidad'),
            preserve_default=False,
        ),
    ]
