# Generated by Django 4.0.4 on 2022-05-10 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0036_remove_owner_unidad_unidad_propietario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plazos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(max_length=12, verbose_name='Plazos')),
            ],
        ),
        migrations.AddField(
            model_name='unidad',
            name='tasa',
            field=models.PositiveIntegerField(default=1, max_length=100, verbose_name='Tasa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidad',
            name='valor',
            field=models.PositiveIntegerField(default=1, verbose_name='Valor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidad',
            name='plazo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='arrendadora.plazos'),
            preserve_default=False,
        ),
    ]
