# Generated by Django 4.0.4 on 2022-05-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0037_plazos_unidad_tasa_unidad_valor_unidad_plazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plazos',
            name='name',
            field=models.IntegerField(verbose_name='Plazos'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='tasa',
            field=models.PositiveIntegerField(verbose_name='Tasa'),
        ),
    ]
