# Generated by Django 4.0.4 on 2022-05-10 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0038_alter_plazos_name_alter_unidad_tasa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidad',
            name='plazo',
        ),
    ]
