# Generated by Django 4.0.4 on 2022-05-10 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0039_remove_unidad_plazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='plazo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='arrendadora.plazos'),
            preserve_default=False,
        ),
    ]
