# Generated by Django 4.0.4 on 2022-05-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0040_unidad_plazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='plazo',
            field=models.PositiveIntegerField(verbose_name='Plazo'),
        ),
        migrations.DeleteModel(
            name='Plazos',
        ),
    ]
