# Generated by Django 4.0.4 on 2022-05-10 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0042_factura'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Factura',
            new_name='EstadoDeCuenta',
        ),
    ]
