# Generated by Django 4.0.4 on 2022-05-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0043_rename_factura_estadodecuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadodecuenta',
            name='ref',
            field=models.CharField(default=1, max_length=150, verbose_name='ref'),
            preserve_default=False,
        ),
    ]
