# Generated by Django 4.0.4 on 2022-05-10 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrendadora', '0045_registros'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EstadoDeCuenta',
            new_name='AccountStatus',
        ),
        migrations.RenameModel(
            old_name='Registros',
            new_name='Register',
        ),
    ]
